### ISSUE TITLE
Getting Method is not implemented error 

### ISSUE THREAD

**Issue by uschouhan** [AppiumTestDistribution/appium-interceptor-plugin#42]
appium verion = 2.10.3
interceptor version = appium-interceptor@1.0.0-b

**Code** -
      ((JavascriptExecutor) DriverManager.getDriver()).executeScript("interceptor: startListening");
        Thread.sleep(5000);

        // Configure the mock response
        Map<String, Object> config = new HashMap<>();
        config.put("url", "**/v4/watchlist");
        config.put("statusCode", Integer.valueOf(401));
        // Add the mock using the interceptor
        ((JavascriptExecutor) DriverManager.getDriver()).executeScript("interceptor:addMock", new HashMap<String, Object>() {{
            put("config", config);
        }});

        // Trigger the network request in the app
        homePage.clickWatchlistFooter();
        Thread.sleep(5000);

        // Stop listening and capture the API requests
        List<Map<String, Object>> apiRequests = (List<Map<String, Object>>) ((JavascriptExecutor) DriverManager.getDriver()).executeScript("interceptor:stopListening");

**Exception** ->
[e19c5795][AndroidUiautomator2Driver@9b02] Encountered internal error running command: NotImplementedError: Method is not implemented
    at AndroidUiautomator2Driver.execute (/Users/upendra.chouhan/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/execute.js:121:11)
    at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:106:18)
    at /opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:306:31)
    at exec (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:189:3)
    at AndroidUiautomator2Driver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:122:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1123:14)
    at AppiumInterceptorPlugin.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-plugin/lib/plugin.js:73:14)

**Comment by sudharsan-selvaraj** [comment]
@uschouhan There is a typo in the command name. Replace the command name with `interceptor: addMock` and give it a try.

**Comment by sudharsan-selvaraj** [comment]
This looks like a known issue https://github.com/AppiumTestDistribution/appium-interceptor-plugin/issues/40. we will look into it.
